version: '2'
services:
    atolye-app:
        image: atolye
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://atolye-mariadb:3306/atolye
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=atolye-elasticsearch:9300
        ports:
            - 8080:8080
    atolye-mariadb:
        extends:
            file: mariadb.yml
            service: atolye-mariadb
    atolye-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: atolye-elasticsearch
